# Generated by Django 5.1.7 on 2025-03-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0004_alter_user_managers_alter_user_email"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
