# Generated by Django 5.1.7 on 2025-03-31 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0006_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
